# Generated by Django 4.1.7 on 2023-03-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_1', models.CharField(max_length=1000)),
                ('paragraph_2', models.CharField(max_length=1000)),
                ('paragraph_3', models.CharField(max_length=1000)),
                ('paragraph_4', models.CharField(max_length=1000)),
                ('paragraph_5', models.CharField(blank=True, max_length=1000, null=True)),
                ('paragraph_6', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
