# Generated by Django 4.1.7 on 2023-03-10 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desciption', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('pictured_persons', models.CharField(max_length=500)),
                ('pictured_place', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('uploaded', models.DateTimeField(auto_now=True)),
                ('photo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.phototype')),
            ],
        ),
    ]
