# Generated by Django 4.1.7 on 2023-03-18 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_type_set', to='portfolio.phototype'),
        ),
        migrations.CreateModel(
            name='CoverPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_photo', to='portfolio.photo')),
                ('photo_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_photo_type', to='portfolio.phototype')),
            ],
        ),
    ]
