# Generated by Django 4.1.7 on 2023-03-18 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_photo_photo_type_coverphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverphoto',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
