# Generated by Django 4.1.7 on 2023-03-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_photo_description_alter_photo_pictured_persons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='landscape',
            field=models.BooleanField(default=False),
        ),
    ]
