# Generated by Django 4.1.7 on 2024-07-15 18:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0006_privatephotocategory_privatephoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatephotocategory',
            name='url_slug',
            field=models.SlugField(blank=True, help_text='URL slug for the category (this will be used in the URL to access the category)', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='privatephoto',
            name='image',
            field=models.ImageField(blank=True, help_text='The photo', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='privatephoto',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the photo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='privatephotocategory',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users allowed to view this category', related_name='allowed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatephotocategory',
            name='description',
            field=models.CharField(blank=True, help_text='Description of the category', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='privatephotocategory',
            name='name',
            field=models.CharField(blank=True, help_text='Name of the category', max_length=50, null=True),
        ),
    ]
